### ISSUE TITLE
Simple test should be easier to code

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca-api#134]
In order to allow more people to write their own exercises, providing a simpler interface for entering a test is essential. 

Nowadays, the content writer must have a deep understanding of the language, test framework and/or runner details in order to write their own tests. 

We should be able to enter simple tests as fixture-tables, using a clean an simple UI. It should translate to a simple, generic, cross-language spec of a test, like the following: 

## Testing a function

```yaml
subject:  succ
examples: 
- arguments: 
   - 1
 return: 2
- arguments: 
   - 4
 return: 5
```

## Testing a procedure that performs I/O

```yaml
subject:  echo
examples: 
- input: helllo
  output: hello
- input: world 
  output: world
```

## Testing a program that performs I/O

```yaml
examples: 
- input: helllo
  output: hello
- input: world 
  output: world
```

## Others

We should still define how we want to declare testing of subroutines that perfom some kind of modification of a global matricial state, like in gobstones, SQL or QSIM.  

See https://github.com/flbulgarelli/tester
